# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lex\py_proj\survillace_generator\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 801)
        MainWindow.setMinimumSize(QtCore.QSize(1153, 801))
        MainWindow.setMaximumSize(QtCore.QSize(1153, 825))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabPage = QtWidgets.QTabWidget(self.centralwidget)
        self.tabPage.setObjectName("tabPage")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.cb1 = QtWidgets.QComboBox(self.tab1)
        self.cb1.setGeometry(QtCore.QRect(1010, 710, 111, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.cb1.setFont(font)
        self.cb1.setObjectName("cb1")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1131, 701))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.pageLayout1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.pageLayout1.setContentsMargins(0, 0, 0, 0)
        self.pageLayout1.setObjectName("pageLayout1")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(840, 340, 271, 161))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label1_4 = QtWidgets.QLabel(self.frame_13)
        self.label1_4.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_4.setObjectName("label1_4")
        self.pushButton1_4 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton1_4.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_4.setObjectName("pushButton1_4")
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setGeometry(QtCore.QRect(840, 0, 271, 161))
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label1_2 = QtWidgets.QLabel(self.frame_15)
        self.label1_2.setGeometry(QtCore.QRect(13, 4, 251, 151))
        self.label1_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_2.setObjectName("label1_2")
        self.pushButton1_2 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton1_2.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.frame1_11 = QtWidgets.QFrame(self.frame)
        self.frame1_11.setGeometry(QtCore.QRect(560, 510, 271, 161))
        self.frame1_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1_11.setObjectName("frame1_11")
        self.label1_7 = QtWidgets.QLabel(self.frame1_11)
        self.label1_7.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_7.setObjectName("label1_7")
        self.pushButton1_7 = QtWidgets.QPushButton(self.frame1_11)
        self.pushButton1_7.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_7.setObjectName("pushButton1_7")
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setGeometry(QtCore.QRect(840, 510, 271, 161))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label1_8 = QtWidgets.QLabel(self.frame_12)
        self.label1_8.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_8.setObjectName("label1_8")
        self.pushButton1_8 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton1_8.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_8.setObjectName("pushButton1_8")
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setGeometry(QtCore.QRect(840, 170, 271, 161))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label1_3 = QtWidgets.QLabel(self.frame_14)
        self.label1_3.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_3.setObjectName("label1_3")
        self.pushButton1_3 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton1_3.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_3.setObjectName("pushButton1_3")
        self.frame1_10 = QtWidgets.QFrame(self.frame)
        self.frame1_10.setGeometry(QtCore.QRect(280, 510, 271, 161))
        self.frame1_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1_10.setObjectName("frame1_10")
        self.label1_6 = QtWidgets.QLabel(self.frame1_10)
        self.label1_6.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_6.setObjectName("label1_6")
        self.pushButton1_6 = QtWidgets.QPushButton(self.frame1_10)
        self.pushButton1_6.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_6.setObjectName("pushButton1_6")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(0, 510, 271, 161))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label1_5 = QtWidgets.QLabel(self.frame_9)
        self.label1_5.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_5.setObjectName("label1_5")
        self.pushButton1_5 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton1_5.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_5.setObjectName("pushButton1_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 831, 501))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label1_1 = QtWidgets.QLabel(self.frame_2)
        self.label1_1.setGeometry(QtCore.QRect(10, 10, 811, 481))
        self.label1_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_1.setObjectName("label1_1")
        self.pushButton1_1 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton1_1.setGeometry(QtCore.QRect(720, 470, 101, 23))
        self.pushButton1_1.setObjectName("pushButton1_1")
        self.pageLayout1.addWidget(self.frame)
        self.progressBar = QtWidgets.QProgressBar(self.tab1)
        self.progressBar.setGeometry(QtCore.QRect(0, 710, 941, 20))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tabPage.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.cb2 = QtWidgets.QComboBox(self.tab2)
        self.cb2.setGeometry(QtCore.QRect(1010, 710, 101, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.cb2.setFont(font)
        self.cb2.setObjectName("cb2")
        self.cb2.addItem("")
        self.cb2.addItem("")
        self.cb2.addItem("")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1131, 701))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_73 = QtWidgets.QFrame(self.frame_4)
        self.frame_73.setGeometry(QtCore.QRect(20, 430, 211, 131))
        self.frame_73.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_73.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_73.setObjectName("frame_73")
        self.label_102 = QtWidgets.QLabel(self.frame_73)
        self.label_102.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName("label_102")
        self.pushButton_102 = QtWidgets.QPushButton(self.frame_73)
        self.pushButton_102.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_102.setObjectName("pushButton_102")
        self.frame_18 = QtWidgets.QFrame(self.frame_4)
        self.frame_18.setGeometry(QtCore.QRect(20, 10, 211, 131))
        self.frame_18.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_11 = QtWidgets.QLabel(self.frame_18)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.frame_74 = QtWidgets.QFrame(self.frame_4)
        self.frame_74.setGeometry(QtCore.QRect(680, 430, 211, 131))
        self.frame_74.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_74.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_74.setObjectName("frame_74")
        self.label_103 = QtWidgets.QLabel(self.frame_74)
        self.label_103.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName("label_103")
        self.pushButton_103 = QtWidgets.QPushButton(self.frame_74)
        self.pushButton_103.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_103.setObjectName("pushButton_103")
        self.frame_75 = QtWidgets.QFrame(self.frame_4)
        self.frame_75.setGeometry(QtCore.QRect(900, 430, 211, 131))
        self.frame_75.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_75.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_75.setObjectName("frame_75")
        self.label_104 = QtWidgets.QLabel(self.frame_75)
        self.label_104.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_104.setAlignment(QtCore.Qt.AlignCenter)
        self.label_104.setObjectName("label_104")
        self.pushButton_104 = QtWidgets.QPushButton(self.frame_75)
        self.pushButton_104.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_104.setObjectName("pushButton_104")
        self.frame_76 = QtWidgets.QFrame(self.frame_4)
        self.frame_76.setGeometry(QtCore.QRect(680, 570, 211, 131))
        self.frame_76.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_76.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_76.setObjectName("frame_76")
        self.label_105 = QtWidgets.QLabel(self.frame_76)
        self.label_105.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_105.setAlignment(QtCore.Qt.AlignCenter)
        self.label_105.setObjectName("label_105")
        self.pushButton_105 = QtWidgets.QPushButton(self.frame_76)
        self.pushButton_105.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_105.setObjectName("pushButton_105")
        self.frame_77 = QtWidgets.QFrame(self.frame_4)
        self.frame_77.setGeometry(QtCore.QRect(900, 10, 211, 131))
        self.frame_77.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_77.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_77.setObjectName("frame_77")
        self.label_106 = QtWidgets.QLabel(self.frame_77)
        self.label_106.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_106.setAlignment(QtCore.Qt.AlignCenter)
        self.label_106.setObjectName("label_106")
        self.pushButton_106 = QtWidgets.QPushButton(self.frame_77)
        self.pushButton_106.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_106.setObjectName("pushButton_106")
        self.frame_78 = QtWidgets.QFrame(self.frame_4)
        self.frame_78.setGeometry(QtCore.QRect(460, 150, 211, 131))
        self.frame_78.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_78.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_78.setObjectName("frame_78")
        self.label_107 = QtWidgets.QLabel(self.frame_78)
        self.label_107.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_107.setAlignment(QtCore.Qt.AlignCenter)
        self.label_107.setObjectName("label_107")
        self.pushButton_107 = QtWidgets.QPushButton(self.frame_78)
        self.pushButton_107.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_107.setObjectName("pushButton_107")
        self.frame_79 = QtWidgets.QFrame(self.frame_4)
        self.frame_79.setGeometry(QtCore.QRect(240, 150, 211, 131))
        self.frame_79.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_79.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_79.setObjectName("frame_79")
        self.label_108 = QtWidgets.QLabel(self.frame_79)
        self.label_108.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_108.setAlignment(QtCore.Qt.AlignCenter)
        self.label_108.setObjectName("label_108")
        self.pushButton_108 = QtWidgets.QPushButton(self.frame_79)
        self.pushButton_108.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_108.setObjectName("pushButton_108")
        self.frame_80 = QtWidgets.QFrame(self.frame_4)
        self.frame_80.setGeometry(QtCore.QRect(20, 570, 211, 131))
        self.frame_80.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_80.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_80.setObjectName("frame_80")
        self.label_109 = QtWidgets.QLabel(self.frame_80)
        self.label_109.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_109.setAlignment(QtCore.Qt.AlignCenter)
        self.label_109.setObjectName("label_109")
        self.pushButton_109 = QtWidgets.QPushButton(self.frame_80)
        self.pushButton_109.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_109.setObjectName("pushButton_109")
        self.frame_81 = QtWidgets.QFrame(self.frame_4)
        self.frame_81.setGeometry(QtCore.QRect(900, 150, 211, 131))
        self.frame_81.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_81.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_81.setObjectName("frame_81")
        self.label_110 = QtWidgets.QLabel(self.frame_81)
        self.label_110.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_110.setAlignment(QtCore.Qt.AlignCenter)
        self.label_110.setObjectName("label_110")
        self.pushButton_110 = QtWidgets.QPushButton(self.frame_81)
        self.pushButton_110.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_110.setObjectName("pushButton_110")
        self.frame_82 = QtWidgets.QFrame(self.frame_4)
        self.frame_82.setGeometry(QtCore.QRect(680, 10, 211, 131))
        self.frame_82.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_82.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_82.setObjectName("frame_82")
        self.label_111 = QtWidgets.QLabel(self.frame_82)
        self.label_111.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_111.setAlignment(QtCore.Qt.AlignCenter)
        self.label_111.setObjectName("label_111")
        self.pushButton_111 = QtWidgets.QPushButton(self.frame_82)
        self.pushButton_111.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_111.setObjectName("pushButton_111")
        self.frame_83 = QtWidgets.QFrame(self.frame_4)
        self.frame_83.setGeometry(QtCore.QRect(460, 290, 211, 131))
        self.frame_83.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_83.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_83.setObjectName("frame_83")
        self.label_112 = QtWidgets.QLabel(self.frame_83)
        self.label_112.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_112.setAlignment(QtCore.Qt.AlignCenter)
        self.label_112.setObjectName("label_112")
        self.pushButton_112 = QtWidgets.QPushButton(self.frame_83)
        self.pushButton_112.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_112.setObjectName("pushButton_112")
        self.frame_84 = QtWidgets.QFrame(self.frame_4)
        self.frame_84.setGeometry(QtCore.QRect(460, 10, 211, 131))
        self.frame_84.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_84.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_84.setObjectName("frame_84")
        self.label_113 = QtWidgets.QLabel(self.frame_84)
        self.label_113.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_113.setAlignment(QtCore.Qt.AlignCenter)
        self.label_113.setObjectName("label_113")
        self.pushButton_113 = QtWidgets.QPushButton(self.frame_84)
        self.pushButton_113.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_113.setObjectName("pushButton_113")
        self.frame_85 = QtWidgets.QFrame(self.frame_4)
        self.frame_85.setGeometry(QtCore.QRect(680, 290, 211, 131))
        self.frame_85.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_85.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_85.setObjectName("frame_85")
        self.label_114 = QtWidgets.QLabel(self.frame_85)
        self.label_114.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_114.setAlignment(QtCore.Qt.AlignCenter)
        self.label_114.setObjectName("label_114")
        self.pushButton_114 = QtWidgets.QPushButton(self.frame_85)
        self.pushButton_114.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_114.setObjectName("pushButton_114")
        self.frame_86 = QtWidgets.QFrame(self.frame_4)
        self.frame_86.setGeometry(QtCore.QRect(240, 430, 211, 131))
        self.frame_86.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_86.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_86.setObjectName("frame_86")
        self.label_115 = QtWidgets.QLabel(self.frame_86)
        self.label_115.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_115.setAlignment(QtCore.Qt.AlignCenter)
        self.label_115.setObjectName("label_115")
        self.pushButton_115 = QtWidgets.QPushButton(self.frame_86)
        self.pushButton_115.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_115.setObjectName("pushButton_115")
        self.frame_87 = QtWidgets.QFrame(self.frame_4)
        self.frame_87.setGeometry(QtCore.QRect(900, 570, 211, 131))
        self.frame_87.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_87.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_87.setObjectName("frame_87")
        self.label_116 = QtWidgets.QLabel(self.frame_87)
        self.label_116.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_116.setAlignment(QtCore.Qt.AlignCenter)
        self.label_116.setObjectName("label_116")
        self.pushButton_116 = QtWidgets.QPushButton(self.frame_87)
        self.pushButton_116.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_116.setObjectName("pushButton_116")
        self.frame_88 = QtWidgets.QFrame(self.frame_4)
        self.frame_88.setGeometry(QtCore.QRect(240, 290, 211, 131))
        self.frame_88.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_88.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_88.setObjectName("frame_88")
        self.label_117 = QtWidgets.QLabel(self.frame_88)
        self.label_117.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_117.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_117.setAlignment(QtCore.Qt.AlignCenter)
        self.label_117.setObjectName("label_117")
        self.pushButton_117 = QtWidgets.QPushButton(self.frame_88)
        self.pushButton_117.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_117.setObjectName("pushButton_117")
        self.frame_89 = QtWidgets.QFrame(self.frame_4)
        self.frame_89.setGeometry(QtCore.QRect(460, 570, 211, 131))
        self.frame_89.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_89.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_89.setObjectName("frame_89")
        self.label_118 = QtWidgets.QLabel(self.frame_89)
        self.label_118.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_118.setAlignment(QtCore.Qt.AlignCenter)
        self.label_118.setObjectName("label_118")
        self.pushButton_118 = QtWidgets.QPushButton(self.frame_89)
        self.pushButton_118.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_118.setObjectName("pushButton_118")
        self.frame_90 = QtWidgets.QFrame(self.frame_4)
        self.frame_90.setGeometry(QtCore.QRect(20, 150, 211, 131))
        self.frame_90.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_90.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_90.setObjectName("frame_90")
        self.label_119 = QtWidgets.QLabel(self.frame_90)
        self.label_119.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_119.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_119.setAlignment(QtCore.Qt.AlignCenter)
        self.label_119.setObjectName("label_119")
        self.pushButton_119 = QtWidgets.QPushButton(self.frame_90)
        self.pushButton_119.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_119.setObjectName("pushButton_119")
        self.frame_91 = QtWidgets.QFrame(self.frame_4)
        self.frame_91.setGeometry(QtCore.QRect(460, 430, 211, 131))
        self.frame_91.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_91.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_91.setObjectName("frame_91")
        self.label_120 = QtWidgets.QLabel(self.frame_91)
        self.label_120.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_120.setAlignment(QtCore.Qt.AlignCenter)
        self.label_120.setObjectName("label_120")
        self.pushButton_120 = QtWidgets.QPushButton(self.frame_91)
        self.pushButton_120.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_120.setObjectName("pushButton_120")
        self.frame_38 = QtWidgets.QFrame(self.frame_4)
        self.frame_38.setGeometry(QtCore.QRect(240, 10, 211, 131))
        self.frame_38.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.label_121 = QtWidgets.QLabel(self.frame_38)
        self.label_121.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_121.setAlignment(QtCore.Qt.AlignCenter)
        self.label_121.setObjectName("label_121")
        self.pushButton_121 = QtWidgets.QPushButton(self.frame_38)
        self.pushButton_121.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_121.setObjectName("pushButton_121")
        self.frame_92 = QtWidgets.QFrame(self.frame_4)
        self.frame_92.setGeometry(QtCore.QRect(680, 150, 211, 131))
        self.frame_92.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_92.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_92.setObjectName("frame_92")
        self.label_122 = QtWidgets.QLabel(self.frame_92)
        self.label_122.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_122.setAlignment(QtCore.Qt.AlignCenter)
        self.label_122.setObjectName("label_122")
        self.pushButton_122 = QtWidgets.QPushButton(self.frame_92)
        self.pushButton_122.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_122.setObjectName("pushButton_122")
        self.frame_30 = QtWidgets.QFrame(self.frame_4)
        self.frame_30.setGeometry(QtCore.QRect(20, 290, 211, 131))
        self.frame_30.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.label_123 = QtWidgets.QLabel(self.frame_30)
        self.label_123.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_123.setAlignment(QtCore.Qt.AlignCenter)
        self.label_123.setObjectName("label_123")
        self.pushButton_123 = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_123.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_123.setObjectName("pushButton_123")
        self.frame_32 = QtWidgets.QFrame(self.frame_4)
        self.frame_32.setGeometry(QtCore.QRect(240, 570, 211, 131))
        self.frame_32.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.label_124 = QtWidgets.QLabel(self.frame_32)
        self.label_124.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_124.setAlignment(QtCore.Qt.AlignCenter)
        self.label_124.setObjectName("label_124")
        self.pushButton_124 = QtWidgets.QPushButton(self.frame_32)
        self.pushButton_124.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_124.setObjectName("pushButton_124")
        self.frame_93 = QtWidgets.QFrame(self.frame_4)
        self.frame_93.setGeometry(QtCore.QRect(900, 290, 211, 131))
        self.frame_93.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_93.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_93.setObjectName("frame_93")
        self.label_125 = QtWidgets.QLabel(self.frame_93)
        self.label_125.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_125.setAlignment(QtCore.Qt.AlignCenter)
        self.label_125.setObjectName("label_125")
        self.pushButton_125 = QtWidgets.QPushButton(self.frame_93)
        self.pushButton_125.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_125.setObjectName("pushButton_125")
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.tabPage.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1131, 741))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_71 = QtWidgets.QFrame(self.frame_3)
        self.frame_71.setGeometry(QtCore.QRect(20, 430, 211, 131))
        self.frame_71.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_71.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_71.setObjectName("frame_71")
        self.label_100 = QtWidgets.QLabel(self.frame_71)
        self.label_100.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName("label_100")
        self.pushButton_100 = QtWidgets.QPushButton(self.frame_71)
        self.pushButton_100.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_100.setObjectName("pushButton_100")
        self.frame_17 = QtWidgets.QFrame(self.frame_3)
        self.frame_17.setGeometry(QtCore.QRect(20, 10, 211, 131))
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_10 = QtWidgets.QLabel(self.frame_17)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_10.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.frame_69 = QtWidgets.QFrame(self.frame_3)
        self.frame_69.setGeometry(QtCore.QRect(680, 430, 211, 131))
        self.frame_69.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_69.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_69.setObjectName("frame_69")
        self.label_98 = QtWidgets.QLabel(self.frame_69)
        self.label_98.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.pushButton_98 = QtWidgets.QPushButton(self.frame_69)
        self.pushButton_98.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_98.setObjectName("pushButton_98")
        self.frame_55 = QtWidgets.QFrame(self.frame_3)
        self.frame_55.setGeometry(QtCore.QRect(900, 430, 211, 131))
        self.frame_55.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.label_82 = QtWidgets.QLabel(self.frame_55)
        self.label_82.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.pushButton_82 = QtWidgets.QPushButton(self.frame_55)
        self.pushButton_82.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_82.setObjectName("pushButton_82")
        self.frame_67 = QtWidgets.QFrame(self.frame_3)
        self.frame_67.setGeometry(QtCore.QRect(680, 570, 211, 131))
        self.frame_67.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_67.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_67.setObjectName("frame_67")
        self.label_96 = QtWidgets.QLabel(self.frame_67)
        self.label_96.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName("label_96")
        self.pushButton_96 = QtWidgets.QPushButton(self.frame_67)
        self.pushButton_96.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_96.setObjectName("pushButton_96")
        self.frame_60 = QtWidgets.QFrame(self.frame_3)
        self.frame_60.setGeometry(QtCore.QRect(900, 10, 211, 131))
        self.frame_60.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.label_88 = QtWidgets.QLabel(self.frame_60)
        self.label_88.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.pushButton_88 = QtWidgets.QPushButton(self.frame_60)
        self.pushButton_88.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_88.setObjectName("pushButton_88")
        self.frame_65 = QtWidgets.QFrame(self.frame_3)
        self.frame_65.setGeometry(QtCore.QRect(460, 150, 211, 131))
        self.frame_65.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_65.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_65.setObjectName("frame_65")
        self.label_94 = QtWidgets.QLabel(self.frame_65)
        self.label_94.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.pushButton_94 = QtWidgets.QPushButton(self.frame_65)
        self.pushButton_94.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_94.setObjectName("pushButton_94")
        self.frame_62 = QtWidgets.QFrame(self.frame_3)
        self.frame_62.setGeometry(QtCore.QRect(240, 150, 211, 131))
        self.frame_62.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.label_91 = QtWidgets.QLabel(self.frame_62)
        self.label_91.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.pushButton_91 = QtWidgets.QPushButton(self.frame_62)
        self.pushButton_91.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_91.setObjectName("pushButton_91")
        self.frame_70 = QtWidgets.QFrame(self.frame_3)
        self.frame_70.setGeometry(QtCore.QRect(20, 570, 211, 131))
        self.frame_70.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_70.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_70.setObjectName("frame_70")
        self.label_99 = QtWidgets.QLabel(self.frame_70)
        self.label_99.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.pushButton_99 = QtWidgets.QPushButton(self.frame_70)
        self.pushButton_99.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_99.setObjectName("pushButton_99")
        self.frame_61 = QtWidgets.QFrame(self.frame_3)
        self.frame_61.setGeometry(QtCore.QRect(900, 150, 211, 131))
        self.frame_61.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.label_90 = QtWidgets.QLabel(self.frame_61)
        self.label_90.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.pushButton_90 = QtWidgets.QPushButton(self.frame_61)
        self.pushButton_90.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_90.setObjectName("pushButton_90")
        self.frame_59 = QtWidgets.QFrame(self.frame_3)
        self.frame_59.setGeometry(QtCore.QRect(680, 10, 211, 131))
        self.frame_59.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_59.setObjectName("frame_59")
        self.label_87 = QtWidgets.QLabel(self.frame_59)
        self.label_87.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.pushButton_87 = QtWidgets.QPushButton(self.frame_59)
        self.pushButton_87.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_87.setObjectName("pushButton_87")
        self.frame_64 = QtWidgets.QFrame(self.frame_3)
        self.frame_64.setGeometry(QtCore.QRect(460, 290, 211, 131))
        self.frame_64.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.label_93 = QtWidgets.QLabel(self.frame_64)
        self.label_93.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.pushButton_93 = QtWidgets.QPushButton(self.frame_64)
        self.pushButton_93.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_93.setObjectName("pushButton_93")
        self.frame_54 = QtWidgets.QFrame(self.frame_3)
        self.frame_54.setGeometry(QtCore.QRect(460, 10, 211, 131))
        self.frame_54.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.label_81 = QtWidgets.QLabel(self.frame_54)
        self.label_81.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.pushButton_81 = QtWidgets.QPushButton(self.frame_54)
        self.pushButton_81.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_81.setObjectName("pushButton_81")
        self.frame_56 = QtWidgets.QFrame(self.frame_3)
        self.frame_56.setGeometry(QtCore.QRect(680, 290, 211, 131))
        self.frame_56.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.label_83 = QtWidgets.QLabel(self.frame_56)
        self.label_83.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.pushButton_83 = QtWidgets.QPushButton(self.frame_56)
        self.pushButton_83.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_83.setObjectName("pushButton_83")
        self.frame_57 = QtWidgets.QFrame(self.frame_3)
        self.frame_57.setGeometry(QtCore.QRect(240, 430, 211, 131))
        self.frame_57.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.label_85 = QtWidgets.QLabel(self.frame_57)
        self.label_85.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.pushButton_85 = QtWidgets.QPushButton(self.frame_57)
        self.pushButton_85.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_85.setObjectName("pushButton_85")
        self.frame_52 = QtWidgets.QFrame(self.frame_3)
        self.frame_52.setGeometry(QtCore.QRect(900, 570, 211, 131))
        self.frame_52.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.label_79 = QtWidgets.QLabel(self.frame_52)
        self.label_79.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.pushButton_79 = QtWidgets.QPushButton(self.frame_52)
        self.pushButton_79.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_79.setObjectName("pushButton_79")
        self.frame_53 = QtWidgets.QFrame(self.frame_3)
        self.frame_53.setGeometry(QtCore.QRect(240, 290, 211, 131))
        self.frame_53.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.label_80 = QtWidgets.QLabel(self.frame_53)
        self.label_80.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_80.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.pushButton_80 = QtWidgets.QPushButton(self.frame_53)
        self.pushButton_80.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_80.setObjectName("pushButton_80")
        self.frame_63 = QtWidgets.QFrame(self.frame_3)
        self.frame_63.setGeometry(QtCore.QRect(460, 570, 211, 131))
        self.frame_63.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.label_92 = QtWidgets.QLabel(self.frame_63)
        self.label_92.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.pushButton_92 = QtWidgets.QPushButton(self.frame_63)
        self.pushButton_92.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_92.setObjectName("pushButton_92")
        self.frame_68 = QtWidgets.QFrame(self.frame_3)
        self.frame_68.setGeometry(QtCore.QRect(20, 150, 211, 131))
        self.frame_68.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_68.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_68.setObjectName("frame_68")
        self.label_97 = QtWidgets.QLabel(self.frame_68)
        self.label_97.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_97.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName("label_97")
        self.pushButton_97 = QtWidgets.QPushButton(self.frame_68)
        self.pushButton_97.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_97.setObjectName("pushButton_97")
        self.frame_58 = QtWidgets.QFrame(self.frame_3)
        self.frame_58.setGeometry(QtCore.QRect(460, 430, 211, 131))
        self.frame_58.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.label_86 = QtWidgets.QLabel(self.frame_58)
        self.label_86.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.pushButton_86 = QtWidgets.QPushButton(self.frame_58)
        self.pushButton_86.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_86.setObjectName("pushButton_86")
        self.frame_37 = QtWidgets.QFrame(self.frame_3)
        self.frame_37.setGeometry(QtCore.QRect(240, 10, 211, 131))
        self.frame_37.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.label_78 = QtWidgets.QLabel(self.frame_37)
        self.label_78.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.pushButton_78 = QtWidgets.QPushButton(self.frame_37)
        self.pushButton_78.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_78.setObjectName("pushButton_78")
        self.frame_66 = QtWidgets.QFrame(self.frame_3)
        self.frame_66.setGeometry(QtCore.QRect(680, 150, 211, 131))
        self.frame_66.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_66.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_66.setObjectName("frame_66")
        self.label_95 = QtWidgets.QLabel(self.frame_66)
        self.label_95.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.pushButton_95 = QtWidgets.QPushButton(self.frame_66)
        self.pushButton_95.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_95.setObjectName("pushButton_95")
        self.frame_29 = QtWidgets.QFrame(self.frame_3)
        self.frame_29.setGeometry(QtCore.QRect(20, 290, 211, 131))
        self.frame_29.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.label_84 = QtWidgets.QLabel(self.frame_29)
        self.label_84.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.pushButton_84 = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_84.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_84.setObjectName("pushButton_84")
        self.frame_31 = QtWidgets.QFrame(self.frame_3)
        self.frame_31.setGeometry(QtCore.QRect(240, 570, 211, 131))
        self.frame_31.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.label_89 = QtWidgets.QLabel(self.frame_31)
        self.label_89.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.pushButton_89 = QtWidgets.QPushButton(self.frame_31)
        self.pushButton_89.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_89.setObjectName("pushButton_89")
        self.frame_72 = QtWidgets.QFrame(self.frame_3)
        self.frame_72.setGeometry(QtCore.QRect(900, 290, 211, 131))
        self.frame_72.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_72.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_72.setObjectName("frame_72")
        self.label_101 = QtWidgets.QLabel(self.frame_72)
        self.label_101.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName("label_101")
        self.pushButton_101 = QtWidgets.QPushButton(self.frame_72)
        self.pushButton_101.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_101.setObjectName("pushButton_101")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.tabPage.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.tabPage.addTab(self.tab4, "")
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.tabPage.addTab(self.tab5, "")
        self.tab6 = QtWidgets.QWidget()
        self.tab6.setObjectName("tab6")
        self.tabPage.addTab(self.tab6, "")
        self.horizontalLayout.addWidget(self.tabPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actiondaochu = QtWidgets.QAction(MainWindow)
        self.actiondaochu.setObjectName("actiondaochu")
        self.menu.addAction(self.actiondaochu)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabPage.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cb1.setItemText(0, _translate("MainWindow", "八画面"))
        self.cb1.setItemText(1, _translate("MainWindow", "十六画面"))
        self.cb1.setItemText(2, _translate("MainWindow", "二十五画面"))
        self.label1_4.setText(_translate("MainWindow", "图片4"))
        self.pushButton1_4.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_2.setText(_translate("MainWindow", "图片2"))
        self.pushButton1_2.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_7.setText(_translate("MainWindow", "图片7"))
        self.pushButton1_7.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_8.setText(_translate("MainWindow", "图片8"))
        self.pushButton1_8.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_3.setText(_translate("MainWindow", "图片3"))
        self.pushButton1_3.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_6.setText(_translate("MainWindow", "图片6"))
        self.pushButton1_6.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_5.setText(_translate("MainWindow", "图片5"))
        self.pushButton1_5.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_1.setText(_translate("MainWindow", "图片1"))
        self.pushButton1_1.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab1), _translate("MainWindow", "监控1#"))
        self.cb2.setItemText(0, _translate("MainWindow", "八画面"))
        self.cb2.setItemText(1, _translate("MainWindow", "十六画面"))
        self.cb2.setItemText(2, _translate("MainWindow", "二十五画面"))
        self.label_102.setText(_translate("MainWindow", "图片16"))
        self.pushButton_102.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_11.setText(_translate("MainWindow", "图片1"))
        self.pushButton_11.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_103.setText(_translate("MainWindow", "图片19"))
        self.pushButton_103.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_104.setText(_translate("MainWindow", "图片20"))
        self.pushButton_104.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_105.setText(_translate("MainWindow", "图片24"))
        self.pushButton_105.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_106.setText(_translate("MainWindow", "图片5"))
        self.pushButton_106.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_107.setText(_translate("MainWindow", "图片8"))
        self.pushButton_107.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_108.setText(_translate("MainWindow", "图片7"))
        self.pushButton_108.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_109.setText(_translate("MainWindow", "图片21"))
        self.pushButton_109.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_110.setText(_translate("MainWindow", "图片10"))
        self.pushButton_110.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_111.setText(_translate("MainWindow", "图片4"))
        self.pushButton_111.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_112.setText(_translate("MainWindow", "图片13"))
        self.pushButton_112.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_113.setText(_translate("MainWindow", "图片3"))
        self.pushButton_113.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_114.setText(_translate("MainWindow", "图片14"))
        self.pushButton_114.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_115.setText(_translate("MainWindow", "图片17"))
        self.pushButton_115.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_116.setText(_translate("MainWindow", "图片25"))
        self.pushButton_116.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_117.setText(_translate("MainWindow", "图片12"))
        self.pushButton_117.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_118.setText(_translate("MainWindow", "图片23"))
        self.pushButton_118.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_119.setText(_translate("MainWindow", "图片6"))
        self.pushButton_119.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_120.setText(_translate("MainWindow", "图片18"))
        self.pushButton_120.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_121.setText(_translate("MainWindow", "图片2"))
        self.pushButton_121.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_122.setText(_translate("MainWindow", "图片9"))
        self.pushButton_122.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_123.setText(_translate("MainWindow", "图片11"))
        self.pushButton_123.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_124.setText(_translate("MainWindow", "图片22"))
        self.pushButton_124.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_125.setText(_translate("MainWindow", "图片15"))
        self.pushButton_125.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab2), _translate("MainWindow", "监控#2"))
        self.label_100.setText(_translate("MainWindow", "图片16"))
        self.pushButton_100.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_10.setText(_translate("MainWindow", "图片1"))
        self.pushButton_10.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_98.setText(_translate("MainWindow", "图片19"))
        self.pushButton_98.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_82.setText(_translate("MainWindow", "图片20"))
        self.pushButton_82.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_96.setText(_translate("MainWindow", "图片24"))
        self.pushButton_96.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_88.setText(_translate("MainWindow", "图片5"))
        self.pushButton_88.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_94.setText(_translate("MainWindow", "图片8"))
        self.pushButton_94.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_91.setText(_translate("MainWindow", "图片7"))
        self.pushButton_91.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_99.setText(_translate("MainWindow", "图片21"))
        self.pushButton_99.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_90.setText(_translate("MainWindow", "图片10"))
        self.pushButton_90.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_87.setText(_translate("MainWindow", "图片4"))
        self.pushButton_87.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_93.setText(_translate("MainWindow", "图片13"))
        self.pushButton_93.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_81.setText(_translate("MainWindow", "图片3"))
        self.pushButton_81.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_83.setText(_translate("MainWindow", "图片14"))
        self.pushButton_83.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_85.setText(_translate("MainWindow", "图片17"))
        self.pushButton_85.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_79.setText(_translate("MainWindow", "图片25"))
        self.pushButton_79.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_80.setText(_translate("MainWindow", "图片12"))
        self.pushButton_80.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_92.setText(_translate("MainWindow", "图片23"))
        self.pushButton_92.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_97.setText(_translate("MainWindow", "图片6"))
        self.pushButton_97.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_86.setText(_translate("MainWindow", "图片18"))
        self.pushButton_86.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_78.setText(_translate("MainWindow", "图片2"))
        self.pushButton_78.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_95.setText(_translate("MainWindow", "图片9"))
        self.pushButton_95.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_84.setText(_translate("MainWindow", "图片11"))
        self.pushButton_84.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_89.setText(_translate("MainWindow", "图片22"))
        self.pushButton_89.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_101.setText(_translate("MainWindow", "图片15"))
        self.pushButton_101.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab3), _translate("MainWindow", "监控#3"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab4), _translate("MainWindow", "监控#4"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab5), _translate("MainWindow", "监控#5"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab6), _translate("MainWindow", "监控#6"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actiondaochu.setText(_translate("MainWindow", "导出PPT"))
