# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lex Chen\py_proj\survillance_generator\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 825)
        MainWindow.setMinimumSize(QtCore.QSize(1153, 801))
        MainWindow.setMaximumSize(QtCore.QSize(1153, 825))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabPage = QtWidgets.QTabWidget(self.centralwidget)
        self.tabPage.setObjectName("tabPage")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.cb1 = QtWidgets.QComboBox(self.tab1)
        self.cb1.setGeometry(QtCore.QRect(958, 700, 161, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.cb1.setFont(font)
        self.cb1.setObjectName("cb1")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1121, 691))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.pageLayout1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.pageLayout1.setContentsMargins(0, 0, 0, 0)
        self.pageLayout1.setObjectName("pageLayout1")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(840, 340, 271, 161))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label1_4 = QtWidgets.QLabel(self.frame_13)
        self.label1_4.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_4.setObjectName("label1_4")
        self.pushButton1_4 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton1_4.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_4.setObjectName("pushButton1_4")
        self.frame_15 = QtWidgets.QFrame(self.frame)
        self.frame_15.setGeometry(QtCore.QRect(840, 0, 271, 161))
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label1_2 = QtWidgets.QLabel(self.frame_15)
        self.label1_2.setGeometry(QtCore.QRect(13, 4, 251, 151))
        self.label1_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_2.setObjectName("label1_2")
        self.pushButton1_2 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton1_2.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.frame1_11 = QtWidgets.QFrame(self.frame)
        self.frame1_11.setGeometry(QtCore.QRect(560, 510, 271, 161))
        self.frame1_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1_11.setObjectName("frame1_11")
        self.label1_7 = QtWidgets.QLabel(self.frame1_11)
        self.label1_7.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_7.setObjectName("label1_7")
        self.pushButton1_7 = QtWidgets.QPushButton(self.frame1_11)
        self.pushButton1_7.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_7.setObjectName("pushButton1_7")
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setGeometry(QtCore.QRect(840, 510, 271, 161))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label1_8 = QtWidgets.QLabel(self.frame_12)
        self.label1_8.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_8.setObjectName("label1_8")
        self.pushButton1_8 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton1_8.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_8.setObjectName("pushButton1_8")
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setGeometry(QtCore.QRect(840, 170, 271, 161))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label1_3 = QtWidgets.QLabel(self.frame_14)
        self.label1_3.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_3.setObjectName("label1_3")
        self.pushButton1_3 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton1_3.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_3.setObjectName("pushButton1_3")
        self.frame1_10 = QtWidgets.QFrame(self.frame)
        self.frame1_10.setGeometry(QtCore.QRect(280, 510, 271, 161))
        self.frame1_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1_10.setObjectName("frame1_10")
        self.label1_6 = QtWidgets.QLabel(self.frame1_10)
        self.label1_6.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_6.setObjectName("label1_6")
        self.pushButton1_6 = QtWidgets.QPushButton(self.frame1_10)
        self.pushButton1_6.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_6.setObjectName("pushButton1_6")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(0, 510, 271, 161))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label1_5 = QtWidgets.QLabel(self.frame_9)
        self.label1_5.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.label1_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_5.setObjectName("label1_5")
        self.pushButton1_5 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton1_5.setGeometry(QtCore.QRect(160, 130, 101, 23))
        self.pushButton1_5.setObjectName("pushButton1_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 831, 501))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label1_1 = QtWidgets.QLabel(self.frame_2)
        self.label1_1.setGeometry(QtCore.QRect(10, 10, 811, 481))
        self.label1_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_1.setObjectName("label1_1")
        self.pushButton1_1 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton1_1.setGeometry(QtCore.QRect(720, 470, 101, 23))
        self.pushButton1_1.setObjectName("pushButton1_1")
        self.pageLayout1.addWidget(self.frame)
        self.tabPage.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.frame_16 = QtWidgets.QFrame(self.tab2)
        self.frame_16.setGeometry(QtCore.QRect(20, 10, 211, 131))
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_9 = QtWidgets.QLabel(self.frame_16)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_9.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.frame_25 = QtWidgets.QFrame(self.tab2)
        self.frame_25.setGeometry(QtCore.QRect(20, 150, 211, 131))
        self.frame_25.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.label_54 = QtWidgets.QLabel(self.frame_25)
        self.label_54.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_54.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.pushButton_54 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_54.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_54.setObjectName("pushButton_54")
        self.frame_26 = QtWidgets.QFrame(self.tab2)
        self.frame_26.setGeometry(QtCore.QRect(20, 290, 211, 131))
        self.frame_26.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.label_55 = QtWidgets.QLabel(self.frame_26)
        self.label_55.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.pushButton_55 = QtWidgets.QPushButton(self.frame_26)
        self.pushButton_55.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_55.setObjectName("pushButton_55")
        self.frame_27 = QtWidgets.QFrame(self.tab2)
        self.frame_27.setGeometry(QtCore.QRect(20, 430, 211, 131))
        self.frame_27.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.label_56 = QtWidgets.QLabel(self.frame_27)
        self.label_56.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.pushButton_56 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_56.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_56.setObjectName("pushButton_56")
        self.frame_28 = QtWidgets.QFrame(self.tab2)
        self.frame_28.setGeometry(QtCore.QRect(20, 570, 211, 131))
        self.frame_28.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.label_57 = QtWidgets.QLabel(self.frame_28)
        self.label_57.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.pushButton_57 = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_57.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_57.setObjectName("pushButton_57")
        self.frame_35 = QtWidgets.QFrame(self.tab2)
        self.frame_35.setGeometry(QtCore.QRect(240, 290, 211, 131))
        self.frame_35.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.label_62 = QtWidgets.QLabel(self.frame_35)
        self.label_62.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_62.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.pushButton_62 = QtWidgets.QPushButton(self.frame_35)
        self.pushButton_62.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_62.setObjectName("pushButton_62")
        self.frame_30 = QtWidgets.QFrame(self.tab2)
        self.frame_30.setGeometry(QtCore.QRect(240, 570, 211, 131))
        self.frame_30.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.label_58 = QtWidgets.QLabel(self.frame_30)
        self.label_58.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.pushButton_58 = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_58.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_58.setObjectName("pushButton_58")
        self.frame_32 = QtWidgets.QFrame(self.tab2)
        self.frame_32.setGeometry(QtCore.QRect(240, 430, 211, 131))
        self.frame_32.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.label_59 = QtWidgets.QLabel(self.frame_32)
        self.label_59.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.pushButton_59 = QtWidgets.QPushButton(self.frame_32)
        self.pushButton_59.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_59.setObjectName("pushButton_59")
        self.frame_33 = QtWidgets.QFrame(self.tab2)
        self.frame_33.setGeometry(QtCore.QRect(240, 150, 211, 131))
        self.frame_33.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.label_60 = QtWidgets.QLabel(self.frame_33)
        self.label_60.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.pushButton_60 = QtWidgets.QPushButton(self.frame_33)
        self.pushButton_60.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_60.setObjectName("pushButton_60")
        self.frame_34 = QtWidgets.QFrame(self.tab2)
        self.frame_34.setGeometry(QtCore.QRect(240, 10, 211, 131))
        self.frame_34.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.label_61 = QtWidgets.QLabel(self.frame_34)
        self.label_61.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.pushButton_61 = QtWidgets.QPushButton(self.frame_34)
        self.pushButton_61.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_61.setObjectName("pushButton_61")
        self.frame_36 = QtWidgets.QFrame(self.tab2)
        self.frame_36.setGeometry(QtCore.QRect(460, 570, 211, 131))
        self.frame_36.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.label_63 = QtWidgets.QLabel(self.frame_36)
        self.label_63.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.pushButton_63 = QtWidgets.QPushButton(self.frame_36)
        self.pushButton_63.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_63.setObjectName("pushButton_63")
        self.frame_38 = QtWidgets.QFrame(self.tab2)
        self.frame_38.setGeometry(QtCore.QRect(460, 430, 211, 131))
        self.frame_38.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.label_64 = QtWidgets.QLabel(self.frame_38)
        self.label_64.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.pushButton_64 = QtWidgets.QPushButton(self.frame_38)
        self.pushButton_64.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_64.setObjectName("pushButton_64")
        self.frame_39 = QtWidgets.QFrame(self.tab2)
        self.frame_39.setGeometry(QtCore.QRect(460, 150, 211, 131))
        self.frame_39.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.label_65 = QtWidgets.QLabel(self.frame_39)
        self.label_65.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.pushButton_65 = QtWidgets.QPushButton(self.frame_39)
        self.pushButton_65.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_65.setObjectName("pushButton_65")
        self.frame_40 = QtWidgets.QFrame(self.tab2)
        self.frame_40.setGeometry(QtCore.QRect(460, 10, 211, 131))
        self.frame_40.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.label_66 = QtWidgets.QLabel(self.frame_40)
        self.label_66.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.pushButton_66 = QtWidgets.QPushButton(self.frame_40)
        self.pushButton_66.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_66.setObjectName("pushButton_66")
        self.frame_41 = QtWidgets.QFrame(self.tab2)
        self.frame_41.setGeometry(QtCore.QRect(460, 290, 211, 131))
        self.frame_41.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.label_67 = QtWidgets.QLabel(self.frame_41)
        self.label_67.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.pushButton_67 = QtWidgets.QPushButton(self.frame_41)
        self.pushButton_67.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_67.setObjectName("pushButton_67")
        self.frame_42 = QtWidgets.QFrame(self.tab2)
        self.frame_42.setGeometry(QtCore.QRect(680, 570, 211, 131))
        self.frame_42.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.label_68 = QtWidgets.QLabel(self.frame_42)
        self.label_68.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.pushButton_68 = QtWidgets.QPushButton(self.frame_42)
        self.pushButton_68.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_68.setObjectName("pushButton_68")
        self.frame_43 = QtWidgets.QFrame(self.tab2)
        self.frame_43.setGeometry(QtCore.QRect(680, 430, 211, 131))
        self.frame_43.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.label_69 = QtWidgets.QLabel(self.frame_43)
        self.label_69.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.pushButton_69 = QtWidgets.QPushButton(self.frame_43)
        self.pushButton_69.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_69.setObjectName("pushButton_69")
        self.frame_44 = QtWidgets.QFrame(self.tab2)
        self.frame_44.setGeometry(QtCore.QRect(680, 150, 211, 131))
        self.frame_44.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.label_70 = QtWidgets.QLabel(self.frame_44)
        self.label_70.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.pushButton_70 = QtWidgets.QPushButton(self.frame_44)
        self.pushButton_70.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_70.setObjectName("pushButton_70")
        self.frame_45 = QtWidgets.QFrame(self.tab2)
        self.frame_45.setGeometry(QtCore.QRect(680, 10, 211, 131))
        self.frame_45.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.label_71 = QtWidgets.QLabel(self.frame_45)
        self.label_71.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.pushButton_71 = QtWidgets.QPushButton(self.frame_45)
        self.pushButton_71.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_71.setObjectName("pushButton_71")
        self.frame_46 = QtWidgets.QFrame(self.tab2)
        self.frame_46.setGeometry(QtCore.QRect(680, 290, 211, 131))
        self.frame_46.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.label_72 = QtWidgets.QLabel(self.frame_46)
        self.label_72.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.pushButton_72 = QtWidgets.QPushButton(self.frame_46)
        self.pushButton_72.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_72.setObjectName("pushButton_72")
        self.frame_47 = QtWidgets.QFrame(self.tab2)
        self.frame_47.setGeometry(QtCore.QRect(900, 570, 211, 131))
        self.frame_47.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.label_73 = QtWidgets.QLabel(self.frame_47)
        self.label_73.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.pushButton_73 = QtWidgets.QPushButton(self.frame_47)
        self.pushButton_73.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_73.setObjectName("pushButton_73")
        self.frame_48 = QtWidgets.QFrame(self.tab2)
        self.frame_48.setGeometry(QtCore.QRect(900, 430, 211, 131))
        self.frame_48.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.label_74 = QtWidgets.QLabel(self.frame_48)
        self.label_74.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.pushButton_74 = QtWidgets.QPushButton(self.frame_48)
        self.pushButton_74.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_74.setObjectName("pushButton_74")
        self.frame_49 = QtWidgets.QFrame(self.tab2)
        self.frame_49.setGeometry(QtCore.QRect(900, 150, 211, 131))
        self.frame_49.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.label_75 = QtWidgets.QLabel(self.frame_49)
        self.label_75.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.pushButton_75 = QtWidgets.QPushButton(self.frame_49)
        self.pushButton_75.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_75.setObjectName("pushButton_75")
        self.frame_50 = QtWidgets.QFrame(self.tab2)
        self.frame_50.setGeometry(QtCore.QRect(900, 10, 211, 131))
        self.frame_50.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.label_76 = QtWidgets.QLabel(self.frame_50)
        self.label_76.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.pushButton_76 = QtWidgets.QPushButton(self.frame_50)
        self.pushButton_76.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_76.setObjectName("pushButton_76")
        self.frame_51 = QtWidgets.QFrame(self.tab2)
        self.frame_51.setGeometry(QtCore.QRect(900, 290, 211, 131))
        self.frame_51.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.label_77 = QtWidgets.QLabel(self.frame_51)
        self.label_77.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.pushButton_77 = QtWidgets.QPushButton(self.frame_51)
        self.pushButton_77.setGeometry(QtCore.QRect(100, 100, 101, 23))
        self.pushButton_77.setObjectName("pushButton_77")
        self.tabPage.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.tabPage.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.tabPage.addTab(self.tab4, "")
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.tabPage.addTab(self.tab5, "")
        self.tab6 = QtWidgets.QWidget()
        self.tab6.setObjectName("tab6")
        self.tabPage.addTab(self.tab6, "")
        self.horizontalLayout.addWidget(self.tabPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiondaochu = QtWidgets.QAction(MainWindow)
        self.actiondaochu.setObjectName("actiondaochu")
        self.menu.addAction(self.actiondaochu)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabPage.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cb1.setItemText(0, _translate("MainWindow", "八画面"))
        self.cb1.setItemText(1, _translate("MainWindow", "十六画面"))
        self.cb1.setItemText(2, _translate("MainWindow", "二十五画面"))
        self.label1_4.setText(_translate("MainWindow", "图片4"))
        self.pushButton1_4.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_2.setText(_translate("MainWindow", "图片2"))
        self.pushButton1_2.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_7.setText(_translate("MainWindow", "图片7"))
        self.pushButton1_7.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_8.setText(_translate("MainWindow", "图片8"))
        self.pushButton1_8.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_3.setText(_translate("MainWindow", "图片3"))
        self.pushButton1_3.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_6.setText(_translate("MainWindow", "图片6"))
        self.pushButton1_6.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_5.setText(_translate("MainWindow", "图片5"))
        self.pushButton1_5.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label1_1.setText(_translate("MainWindow", "图片1"))
        self.pushButton1_1.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab1), _translate("MainWindow", "监控1#"))
        self.label_9.setText(_translate("MainWindow", "图片1"))
        self.pushButton_9.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_54.setText(_translate("MainWindow", "图片6"))
        self.pushButton_54.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_55.setText(_translate("MainWindow", "图片11"))
        self.pushButton_55.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_56.setText(_translate("MainWindow", "图片16"))
        self.pushButton_56.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_57.setText(_translate("MainWindow", "图片21"))
        self.pushButton_57.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_62.setText(_translate("MainWindow", "图片12"))
        self.pushButton_62.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_58.setText(_translate("MainWindow", "图片22"))
        self.pushButton_58.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_59.setText(_translate("MainWindow", "图片17"))
        self.pushButton_59.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_60.setText(_translate("MainWindow", "图片7"))
        self.pushButton_60.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_61.setText(_translate("MainWindow", "图片2"))
        self.pushButton_61.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_63.setText(_translate("MainWindow", "图片23"))
        self.pushButton_63.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_64.setText(_translate("MainWindow", "图片18"))
        self.pushButton_64.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_65.setText(_translate("MainWindow", "图片8"))
        self.pushButton_65.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_66.setText(_translate("MainWindow", "图片3"))
        self.pushButton_66.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_67.setText(_translate("MainWindow", "图片13"))
        self.pushButton_67.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_68.setText(_translate("MainWindow", "图片24"))
        self.pushButton_68.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_69.setText(_translate("MainWindow", "图片19"))
        self.pushButton_69.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_70.setText(_translate("MainWindow", "图片9"))
        self.pushButton_70.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_71.setText(_translate("MainWindow", "图片4"))
        self.pushButton_71.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_72.setText(_translate("MainWindow", "图片14"))
        self.pushButton_72.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_73.setText(_translate("MainWindow", "图片25"))
        self.pushButton_73.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_74.setText(_translate("MainWindow", "图片20"))
        self.pushButton_74.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_75.setText(_translate("MainWindow", "图片10"))
        self.pushButton_75.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_76.setText(_translate("MainWindow", "图片5"))
        self.pushButton_76.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.label_77.setText(_translate("MainWindow", "图片15"))
        self.pushButton_77.setText(_translate("MainWindow", "插入 / 更改图片"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab2), _translate("MainWindow", "监控#2"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab3), _translate("MainWindow", "监控#3"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab4), _translate("MainWindow", "监控#4"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab5), _translate("MainWindow", "监控#5"))
        self.tabPage.setTabText(self.tabPage.indexOf(self.tab6), _translate("MainWindow", "监控#6"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actiondaochu.setText(_translate("MainWindow", "导出PPT"))
